jobs:
  - job: Mobile
    pool: Default
      
    steps:
      - task: FlutterInstall@0
        inputs:
          mode: 'auto'
          channel: 'stable'
          version: 'latest'

      - task: FlutterBuild@0
        inputs:
          target: 'apk'
          projectDirectory: '.'


      - task: FlutterTest@0
        inputs:
          projectDirectory: '.'