jobs:
  - job: Mobile
    pool: Default
      
    steps:
      

      - task: FlutterBuild@0
        inputs:
          target: 'apk'
          projectDirectory: '.'
          flutterDirectory: 'C:\Users\HarshitSinghSehgal\flutter'


      - task: FlutterTest@0
        inputs:
          projectDirectory: '.'